name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
          
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: |
        cd server/frontend
        npm install
        
    - name: Build React frontend
      run: |
        cd server/frontend
        npm run build
        
    - name: Run Django tests
      run: |
        cd server
        python manage.py test
        
    - name: Run Django migrations
      run: |
        cd server
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Collect static files
      run: |
        cd server
        python manage.py collectstatic --noinput

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        cd server
        docker build -t dealership-app:${{ github.sha }} .
        
    - name: Run security scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $HOME/Library/Caches:/root/.cache/ \
          aquasec/trivy:latest image dealership-app:${{ github.sha }}
      continue-on-error: true
      
    # Uncomment below for actual deployment to cloud platforms
    # - name: Deploy to production
    #   run: |
    #     echo "Deploying application..."
    #     # Add your deployment commands here